export default [
  {
    id: '3',
    label: 'Entrepreneurship Center',
    org: "Saint Mary's University",
    role: 'Technology Assistant (Co-op 3, Full Time)',
    when: 'Sept 2020 - Dec 2020',
    data: 'Maintaining and building the SMUEC Website using wordpress was my 3rd and final Co-Op work placements. My role was to help the current website admin to maintain and create new content for the organization, help with onboarding new clients, create website intake form for web projects done by SMUEC for clients, and fulfil some web projects. I used Wordpress and Divi theme builder which were the tools in use at the organization. It used some aspect of PHP, mostly HTML, CSS and JavaScript allowed to get custom components when necessary. Workload after this co-op increased while my hours went to part-time.',
    img1: '',
    img2: '',
    img3: '',
  },

  {
    id: '5',
    label: 'Bloxo',
    org: 'Bloxo Inc.',
    role: 'Web Developer (Co-op 2, Full Time)',
    when: 'Jan 2020 - Mar 2020',
    data: 'Bloxo is a fast-growing startup that aims to help people be more physically active. They intend to do so by providing a Software As A Service that helps people find activities near them, help them organize and pay for them with just a few clicks. My role at Bloxo was largely as a a Web Application Developer, who would be responsible for helping the Bloxo team with developing, designing and creating content in various environments including front-end, back end, web development, development and testing of the mobile application. I was also the technical communicator of the business to help clients with technical questions regarding the platform. Quality assurance, debugging and better customer support were vital components to providing a well-rounded service so  I was tasked for this and to actively find better implementations and use of new services for the entire Bloxo platform. I used Webflow for Web Development and other tools for content creation.',
    img1: '',
    img2: '',
    img3: '',
  },

  {
    id: '1',
    label: 'Information Technology Systems and Services',
    org: "Saint Mary's University",
    role: 'Helpdesk Student Staff (Part time)',
    when: 'Apr 2017 - Jan 2020',
    data: 'I have worked for ITSS most of my university years. It was a great place to learn how the university functions, and how technology is used throughout all levels of hierarchy , from students to academic and administration. I loved working here because there was always something there to learn, and since it was part of the university, I had a great time managing work loads and education loads. This was one of my starting points in the technology industry.',
    img1: '',
    img2: '',
    img3: '',
  },
  {
    id: '2',
    label: 'Elwood Pens',
    org: 'Elwood Pens Inc.',
    role: 'Technology Developer (Full Time)',
    when: 'Jul 2018 - Aug 2018',
    data: 'Working at Elwood Pens was an amazing experience. You work with friends who understand you and push you forward. Unlike my other web development projects, we used Shopify to make an online retail store website. Learning shopify definitely allowed me to see the power of newer web development environments, which I did not know before. I was able to use my passion for photography on the job. As an in-house content creator, I learned more about product photography which we used heavily on the website and on social media. We also created advertisements for our social media. Apart from the technological side of things, I helped manage stocks and retail store, assisted customers, assist in creating a clothing line, and do a lot of research on various topics.',
    img1: '/elwood_img1.png',
    img2: '/elwood_img2.png',
    img3: '/elwood_img3.png',
  },
  {
    id: '6',
    label: 'Perfolio',
    org: 'Perfolio Inc.',
    role: 'CEO / Designer / Developer / Content Creator (Co-op 1, Full Time, now Part Time)',
    when: 'Jan 2019 - Apr 2019, now resuming in 2022',
    data: 'Perfolio, Initially started as Think Forward was/is a web based service that allows professionals to tell their story using a digital (website) medium. Perfolio aims to provide high fidelity content that goes well with a website to tell a story about the client. This was my first Co-Op learning experience in which I got to start a business, create business plans, check viability of the business and execute plans for the clients.  ',
    img1: '',
    img2: '',
    img3: '',
  },

  {
    id: '4',
    label: 'Entrepreneurship Center',
    org: "Saint Mary's University",
    role: 'Project Manager: Technology (Part time)',
    when: 'Jan 2021 - Aug 2021',
    data: ' After my Co-op with SMUEC in Dec 2020, I stayed on to maintain the website while I had a full course load of studies. Later I realized that my direct supervisor was moving out of province which put most website related responsibilities on me as a part timer. After maintaining the website till March/April, I was told to re-design the entire UI/UX and make the website more appealing and fast as a University wide re-branding was approaching. Since I had taken over the website on WordPress which was made by someone else, many of the styling for the re-brand did not work properly. After spending months on somewhat working styles for the re-brand, I asked my superiors to import the design into the old website structure for refreshment, however this was not implemented by the organization at the end of the day.',
    img1: '',
    img2: '',
    img3: '',
  },

  {
    id: '7',
    label: 'DijiDomain',
    org: 'DijiDomain Inc.',
    role: 'Troubleshooting and repair Engineer (Hardware + Software) (Part Time)',
    when: 'Jan 2017 - Jul 2018',
    data: 'DijiDomain was a small startup being conducted by technology enthusiasts on a part time bases that provided hardware and software troubleshooting for clients at an affordable price. Later we expanded into making applications for small clients.',
    img1: '',
    img2: '',
    img3: '',
  },

  {
    id: '8',
    label: 'Science Safety Advising',
    org: "Saint Mary's University",
    role: 'Assistant',
    when: 'Apr 2016 - Jun 2016',
    data: 'This was my first job in Canada. As an Assistant to the Science Safety Advising Ofiicer, my role was to check the safety infrastructure in science labs and make sure it was functional. We also made sure lab rules were followed by faculty and students alike. Along with safety inspection, we helped with inventory of various science labs, get new equipment in and managed inventory of waste chemical disposal and restricted chemicals available on site stored securely.',
    img1: '',
    img2: '',
    img3: '',
  },
  {
    id: '9',
    label: 'Burke Gaffney Observatory',
    org: "Saint Mary's University",
    role: 'Tour Guide',
    when: 'Dec 2015',
    data: 'This was a small but lovely experience of internship. It was my first year at university and I wanted to continue my passion for science education, so I requested for an unpaid internship as a Tour Guide at the university observatory. This gave me a chance to stargaze with a larger telescope and fairly often and I loved doing it.',
    img1: '',
    img2: '',
    img3: '',
  },
];
